variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - test
  - quality

include:
  - ".gitlab/ci/build-tests-freertos.yml"
  - ".gitlab/ci/build-tests-standard.yml"
  - ".gitlab/ci/quality.yml"
  - ".gitlab/ci/run-tests-standard.yml"
